config/routes.rb
Neodat::Application.routes.draw do
  resources :areams
  root :to => 'areams#index'

end

app/models/aream.rb
require 'nkf'

class Aream < ActiveRecord::Base
self.table_name = 'aream'

before_validation { self.area_k  = NKF.nkf('-w -Z4 -x', area_k) }
validates :entmcn,  length: { maximum: 20 }
validates :entclt,  length: { maximum: 20 }
validates :edtmcn,  length: { maximum: 20 }
validates :edtclt,  length: { maximum: 20 }
validates :area_cd, presence: true, length: { maximum: 04 }, uniqueness: true,
          numericality: true
validates :area_j,  presence: true, length: { maximum: 40 }, uniqueness: true,
          format: { with: /\A[\p{Han}\p{Hiragana}\p{Katakana}]+\z/, allow_blank: true, message: 'は漢字、ひらがな、カタカナのいずれかで入力してください' }
validates :area_a,  presence: true, length: { maximum: 40 }, uniqueness: true,
          format: { with: /\A[\p{Han}\p{Hiragana}\p{Katakana}]+\z/, allow_blank: true, message: 'は漢字、ひらがな、カタカナのいずれかで入力してください' } 
validates :area_k,  presence: true, length: { maximum: 40 }, uniqueness: true,
          format: { with: /\A[\p{Katakana}\ﾞ\u30fc]+\z/, allow_blank: true, message: 'はカタカナで入力してください' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areams_controller.rb
require 'date'

class AreamsController < ApplicationController
  before_action :set_aream, only: [:show, :edit, :update, :destroy]

  # GET /areams
  # GET /areams.json
  def index
    @areams = Aream.order("area_cd ASC")
  end

  # GET /areams/1
  # GET /areams/1.json
  def show
  end

  # GET /areams/new
  def new
    @aream = Aream.new
  end

  # GET /areams/1/edit
  def edit
  end

  # POST /areams
  # POST /areams.json
  def create
    @aream = Aream.new(aream_params)
    @aream.entdate = Time.now
    respond_to do |format|
      if @aream.save
        format.html { redirect_to @aream, notice: 'Aream was successfully created.' }
        format.json { render action: 'show', status: :created, location: @aream }
      else
        format.html { render action: 'new' }
        format.json { render json: @aream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areams/1
  # PATCH/PUT /areams/1.json
  def update
    @aream.edtdate = Time.now
    respond_to do |format|
      if @aream.update(aream_params)
        format.html { redirect_to @aream, notice: 'Aream was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @aream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areams/1
  # DELETE /areams/1.json
  def destroy
    @aream.destroy
    respond_to do |format|
      format.html { redirect_to areams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aream
      @aream = Aream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aream_params
      params.require(:aream).permit(:entdate, :entmcn, :entclt, :edtdate, :edtmcn, :edtclt, :area_cd, :area_j, :area_a, :area_k)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areams_helper.rb
module AreamsHelper
end

app/views/areams/_form.html.erb
<%= form_for(@aream) do |f| %>
  <% if @aream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aream.errors.count, "error") %> prohibited this aream from being saved:</h2>
      <ul>
      <% @aream.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :登録マシン %><br>
    <%= f.text_field :entmcn %>
  </div>
  <div class="field">
    <%= f.label :登録ユーザー %><br>
    <%= f.text_field :entclt %>
  </div>
  <div class="field">
    <%= f.label :更新マシン %><br>
    <%= f.text_field :edtmcn %>
  <div class="field">
    <%= f.label :更新ユーザー %><br>
    <%= f.text_field :edtclt %>
  </div>
  <div class="field">
    <%= f.label :地区コード %><br>
    <%= f.text_field :area_cd, {style: "ime-mode:disabled"} %>
  </div>
  <div class="field">
    <%= f.label :地区名 %><br>
    <%= f.text_field :area_j %>
  </div>
  <div class="field">
    <%= f.label :地区名（略称） %><br>
    <%= f.text_field :area_a %>
  </div>
  <div class="field">
    <%= f.label :地区名（カナ） %><br>
    <%= f.text_field :area_k %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areams/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '確認', @aream %> |
<%= link_to '一覧に戻る', areams_path %>

app/views/areams/index.html.erb
<h1>登録エリア一覧</h1>

<table>
  <thead>
    <tr>
      <th>登録日時</th>
      <th>登録マシン</th>
      <th>登録ユーザー</th>
      <th>更新日時</th>
      <th>更新マシン</th>
      <th>更新ユーザー</th>
      <th>地区コード</th>
      <th>地区名</th>
      <th>地区名（略称）</th>
      <th>地区名（カナ）</th>
    </tr>
  </thead>

  <tbody>
    <% @areams.each do |aream| %>
      <tr>
        <td><%= aream.entdate.to_s(:db) %></td>
        <td><%= aream.entmcn %></td>
        <td><%= aream.entclt %></td>
        <td><%= aream.edtdate.try(:strftime,'%Y-%m-%d %H:%M:%S') %></td>
        <td><%= aream.edtmcn %></td>
        <td><%= aream.edtclt %></td>
        <td><%= aream.area_cd %></td>
        <td><%= aream.area_j %></td>
        <td><%= aream.area_a %></td>
        <td><%= aream.area_k %></td>
        <td><%= link_to '確認', aream %></td>
        <td><%= link_to '編集', edit_aream_path(aream) %></td>
        <td><%= link_to '削除', aream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_aream_path %>

app/views/areams/new.html.erb
<h1>新規エリア登録</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', areams_path %>

app/views/areams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>登録日時:</strong>
  <%= @aream.entdate.to_s(:db) %>
</p>

<p>
  <strong>登録マシン:</strong>
  <%= @aream.entmcn %>
</p>

<p>
  <strong>登録ユーザー:</strong>
  <%= @aream.entclt %>
</p>

<p>
  <strong>更新日時:</strong>
  <%= @aream.edtdate.try(:strftime,'%Y-%m-%d %H:%M:%S') %>
</p>

<p>
  <strong>更新マシン:</strong>
  <%= @aream.edtmcn %>
</p>

<p>
  <strong>更新ユーザー:</strong>
  <%= @aream.edtclt %>
</p>

<p>
  <strong>地区コード:</strong>
  <%= @aream.area_cd %>
</p>

<p>
  <strong>地区名:</strong>
  <%= @aream.area_j %>
</p>

<p>
  <strong>地区名(略称):</strong>
  <%= @aream.area_a %>
</p>

<p>
  <strong>地区名(カナ):</strong>
  <%= @aream.area_k %>
</p>

<%= link_to '編集', edit_aream_path(@aream) %> |
<%= link_to '一覧に戻る', areams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neodat</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>